name: Render Quarto (cheatsheet)

on:
push:
branches: [ main ]
workflow_dispatch:

jobs:
render:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: quarto-dev/quarto-actions/setup@v3
- name: Render cheatsheet HTML
run: quarto render quarto_llm_cheatsheet.qmd –to html
- name: Upload artifact
uses: actions/upload-artifact@v4
with:
name: cheatsheet-site
path: ./_site