name: Render Quarto (HTML + artifacts)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v3
      - name: Render HTML (no code execution)
        run: |
          set -euo pipefail
          quarto --version
          quarto render "quarto_llm_cheatsheet.qmd" --to html --no-execute
          test -f "quarto_llm_cheatsheet.html"
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: html
          if-no-files-found: error
          path: quarto_llm_cheatsheet.html
